name: Build, Release, and Upload to Server

on:
  push:
    branches:
      - main  # Запуск при пуше в основную ветку 

jobs:
  build:
    name: Archive and Upload Resource Packs
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu для выполнения шагов

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Клонируем репозиторий для доступа к его содержимому

      - name: Generate tag and push it
        run: |
          TAG_NAME="v$(date +'%Y%m%d-%H%M%S')"  # Генерируем уникальный тег на основе текущей даты и времени
          git config --global user.name "github-actions[bot]"  # Настройка имени пользователя для создания тега
          git config --global user.email "github-actions[bot]@users.noreply.github.com"  # Настройка email для тега
          git tag $TAG_NAME  # Создаём новый тег в репозитории
          git push origin $TAG_NAME  # Отправляем тег в удалённый репозиторий
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV  # Записываем тег в переменные окружения для дальнейшего использования

      - name: Create archives
        run: |
          mkdir -p archives  # Создаём папку для архивов

          # Перебираем все папки внутри resource_packs/
          for dir in resource_packs/*/; do
            # Убираем лишние символы в названии
            dir_name=$(basename "$dir")
            # Архивируем каждую папку с сохранением структуры
            zip -r "archives/$(echo $dir_name | awk '{print toupper($0)}').zip" "$dir"
          done

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: archives/*.zip
          body: "Автоматическая сборка ресурсов"
          draft: false
          prerelease: false

      - name: Upload files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GLOBAL_FTP_HOST }}
          username: ${{ secrets.GLOBAL_FTP_USERNAME }}
          password: ${{ secrets.GLOBAL_FTP_PASSWORD }}
          source: "archives/*.zip"
          target: "${{ secrets.GLOBAL_FTP_PATH }}"
          strip_components: 1
          overwrite: true
