name: Build, Release, and Upload to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Archive and Upload Resource Packs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate tag and push it
        run: |
          TAG_NAME="v$(date +'%Y%m%d-%H%M%S')"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Create archives
        run: |
          mkdir -p archives
          for dir in resource_packs/*/; do
            dir_name=$(basename "$dir")
            archive_name=$(echo "$dir_name" | awk '{print toupper($0)}')
            (cd "$dir" && zip -r "../../archives/${archive_name}.zip" .)
          done

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: archives/*.zip
          body: "Автоматическая сборка ресурсов"
          draft: false
          prerelease: false

      - name: Remove old archives on server 1 except BlankPack.zip
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GLOBAL_FTP_HOST }}
          username: ${{ secrets.GLOBAL_FTP_USERNAME }}
          password: ${{ secrets.GLOBAL_FTP_PASSWORD }}
          script: |
            find ${{ secrets.GLOBAL_FTP_PATH }} -maxdepth 1 -type f -name "*.zip" ! -name "BlankPack.zip" -delete || true

      - name: Upload files via SCP (server 1)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GLOBAL_FTP_HOST }}
          username: ${{ secrets.GLOBAL_FTP_USERNAME }}
          password: ${{ secrets.GLOBAL_FTP_PASSWORD }}
          source: "archives/*.zip"
          target: "${{ secrets.GLOBAL_FTP_PATH }}"
          strip_components: 1

      - name: Remove old archives on server 2 except BlankPack.zip
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GLOBAL_FTP_HOST }}
          username: ${{ secrets.GLOBAL_FTP_USERNAME }}
          password: ${{ secrets.GLOBAL_FTP_PASSWORD }}
          script: |
            find ${{ secrets.GLOBAL_FTP_PATH2 }} -maxdepth 1 -type f -name "*.zip" ! -name "BlankPack.zip" -delete || true

      - name: Upload files via SCP (server 2)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GLOBAL_FTP_HOST }}
          username: ${{ secrets.GLOBAL_FTP_USERNAME }}
          password: ${{ secrets.GLOBAL_FTP_PASSWORD }}
          source: "archives/*.zip"
          target: "${{ secrets.GLOBAL_FTP_PATH2 }}"
          strip_components: 1
