name: Build and Release Resource Packs

on: push

jobs:
  build:
    name: Archive and Upload Resource Packs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create archives
        run: |
          mkdir -p archives
          zip -r archives/mc.projectbw.ru.zip resource_packs/mc.projectbw.ru
          zip -r archives/rc.projectbw.ru.zip resource_packs/rc.projectbw.ru
          zip -r archives/sb.projectbw.ru.zip resource_packs/sb.projectbw.ru
          zip -r archives/mg.projectbw.ru.zip resource_packs/mg.projectbw.ru

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: archives/*.zip
          body: "Автоматическая сборка ресурсов"
          draft: false
          prerelease: false       