name: Build, Release, and Upload to Server

on:
  push:
    branches:
      - main  # Запуск при пуше в основную ветку

jobs:
  build:
    name: Archive and Upload Resource Packs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate tag and push it
        run: |
          TAG_NAME="v$(date +'%Y%m%d-%H%M%S')"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Create archives
        run: |
          mkdir -p archives
          zip -r archives/MC.PROJECTBW.RU.zip resource_packs/mc.projectbw.ru
          zip -r archives/RC.PROJECTBW.RU.zip resource_packs/rc.projectbw.ru
          zip -r archives/SB.PROJECTBW.RU.zip resource_packs/sb.projectbw.ru
          zip -r archives/MG.PROJECTBW.RU.zip resource_packs/mg.projectbw.ru

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: archives/*.zip
          body: "Автоматическая сборка ресурсов"
          draft: false
          prerelease: false

      - name: Upload files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GLOBAL_FTP_HOST }}
          username: ${{ secrets.GLOBAL_FTP_USERNAME }}
          password: ${{ secrets.GLOBAL_FTP_PASSWORD }}
          source: "archives/*.zip"
          target: "${{ secrets.GLOBAL_FTP_PATH }}"
          strip_components: 1  # Убирает лишние пути, чтобы файлы не оказывались в subdir
