name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GLOBAL_API_TOKEN_GITHUB }}
      with:
        source_file: 'resource_packs/mc.projectbw.ru/'
        destination_repo: 'bwproject/RP_MC.PROJECTBW.RU'
        destination_folder: 'resource_packs/mc.projectbw.ru/'
        user_email: 'bwgit@projectbw.ru'
        user_name: 'bwproject'
        commit_message: 'A custom message for the commit'          