name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes MC.PROJECTBW.RU
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GLOBAL_API_TOKEN_GITHUB }}
      with:
        source_file: 'resource_packs/mc.projectbw.ru/'
        destination_repo: 'bwproject/RP_MC.PROJECTBW.RU'
        destination_folder: 'resource_packs/'
        user_email: 'bwgit@projectbw.ru'
        user_name: 'bwproject'
        commit_message: 'update MC'  

    - name: Pushes SB.PROJECTBW.RU
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GLOBAL_API_TOKEN_GITHUB }}
      with:
        source_file: 'resource_packs/sb.projectbw.ru/'
        destination_repo: 'bwproject/RP_SB.PROJECTBW.RU'
        destination_folder: 'resource_packs/'
        user_email: 'bwgit@projectbw.ru'
        user_name: 'bwproject'
        commit_message: 'update SB'  

    - name: Pushes RC.PROJECTBW.RU
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GLOBAL_API_TOKEN_GITHUB }}
      with:
        source_file: 'resource_packs/rc.projectbw.ru/'
        destination_repo: 'bwproject/RP_RC.PROJECTBW.RU'
        destination_folder: 'resource_packs/'
        user_email: 'bwgit@projectbw.ru'
        user_name: 'bwproject'
        commit_message: 'update RC'         