name: Create Archive
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v1.0.0"
          release_name: "ProjectBW_Fonts"
          draft: false
          prerelease: false

      - uses: ksm2/archive-action@v1
        id: archive
        with:
          root-directory: resource_pack  
          format: "zip"
          name: ProjectBW_Fonts
#          include: "**/*.(ts|js|css|html)"

      - uses: sokuhatiku/ftp-upload-artifact@v1
        with:
          name: my-artifact
          path: path/to/artifact/ProjectBW_Fonts.zip
          host: ${{ secrets.FTP_HOST }}
          port: 21
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          secure: false
          remote-path: ${{ secrets.FTP_PATH }}
                 
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.archive.outputs.path }}
          asset_name: ${{ steps.archive.outputs.name }}
          asset_content_type: ${{ steps.archive.outputs.media-type }}

