name: Create Archive
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v1.0.0"
          release_name: "ProjectBW_Fonts"
          draft: false
          prerelease: false

#      - uses: ksm2/archive-action@v1
#        id: archive
#        with:
#          format: "zip"
#          name: ProjectBW_Fonts
#          include: "**/*.(ts|js|css|html)"
#          
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        id: archive
        with:
          type: 'zip'
          filename: 'ProjectBW_Fonts.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'          

      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.archive.outputs.path }}
          asset_name: ${{ steps.archive.outputs.name }}
          asset_content_type: ${{ steps.archive.outputs.media-type }}

