name: Create Resource Pack
#on: [push]
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    
      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
         
      - uses: actions/checkout@v3

      - uses: actions/create-release@v1.1.4
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "ProjectBW_Fonts"
          draft: false
          prerelease: false

      - uses: ksm2/archive-action@v1
        id: archive
        with:
          root-directory: resource_pack  
          format: "zip"
          name: ProjectBW_Fonts
#          include: "**/*.(ts|js|css|html)"
                
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.archive.outputs.path }}
          asset_name: ${{ steps.archive.outputs.name }}
          asset_content_type: ${{ steps.archive.outputs.media-type }}

      - uses: sokuhatiku/ftp-upload-artifact@v1.0.0
        with:
          name: ${{ steps.archive.outputs.name }}
          path: ${{ steps.archive.outputs.path }}
          host: ${{ secrets.FTP_HOST }}
          port: 22
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          secure: false
          remote-path: ${{ secrets.FTP_PATH }}
